/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';

import type { ConfigSourceResult } from '../../../Ast/Data/Result/ConfigSourceResult.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';
import type { CachedConfigFileGeneratorContract } from '../../Config/Contract/CachedConfigFileGeneratorContract.ts';

/**
 * Writes a standalone cached config class.
 *
 * The generated class implements the config contract directly rather than
 * extending a framework config. Extending one would import that base, and a
 * framework config names a component provider in a default parameter value —
 * which loads the whole component provider tree at module load, whether or not
 * the default is ever used. That tree is exactly what a cached application does
 * not need, so the generated config must not reach it by any path.
 *
 * Field initializers are copied as source text, so expressions the author wrote
 * survive unevaluated. Two fields are not copied:
 *
 * - `providers` becomes empty. A cached application reads the generated data and
 *   never walks the provider tree.
 * - `callbacks` becomes a single callback that publishes the generated container
 *   data. The application's own callbacks are dropped, because the callback a
 *   config normally carries is the one that chooses between cached and runtime
 *   publishing — and it lives on a component provider this file must not import.
 */
export class AstCachedConfigFileGenerator extends AstFileGenerator implements CachedConfigFileGeneratorContract {
    /** The service id constant each contract binds under. */
    protected static readonly CONTRACT_SERVICE_IDS: Readonly<Record<string, string>> = {
        ConfigContract: 'ApplicationServiceId.ConfigContract',
        HttpConfigContract: 'ApplicationServiceId.HttpConfigContract',
        CliConfigContract: 'ApplicationServiceId.CliConfigContract',
    };

    protected static readonly APPLICATION_SERVICE_ID =
        '@valkyrjaio/valkyrja/Application/Constant/ApplicationServiceId.ts';

    protected static readonly CONTAINER_SERVICE_ID = '@valkyrjaio/valkyrja/Container/Constant/ContainerServiceId.ts';

    protected static readonly APPLICATION_CONTRACT =
        '@valkyrjaio/valkyrja/Application/Kernel/Contract/ApplicationContract.ts';

    protected static readonly COMPONENT_PROVIDER_CONTRACT =
        '@valkyrjaio/valkyrja/Application/Provider/Contract/ComponentProviderContract.ts';

    /** Fields the generated config replaces rather than copies. */
    protected static readonly REPLACED_FIELDS: readonly string[] = ['providers', 'callbacks'];

    /** Names the generated header already binds, so a copied import must not repeat them. */
    protected static readonly RESERVED_IMPORT_NAMES: readonly string[] = [
        'ApplicationServiceId',
        'ContainerServiceId',
        'ApplicationContract',
        'ComponentProviderContract',
        'ConfigContract',
        'HttpConfigContract',
        'CliConfigContract',
    ];

    /**
     * Fields whose copied value would break the generated config.
     *
     * Debug mode is pinned off rather than copied. In debug mode the routing
     * service provider derives the route collection from the provider tree and
     * writes the result over the routing data. This config has no providers, so
     * that derivation produces an empty collection, and the empty collection
     * replaces the generated data. Every route then fails to match. Debug mode
     * and a cached config are opposite choices, so this file always states the
     * cached one.
     */
    protected static readonly PINNED_FIELDS: Readonly<Record<string, string>> = {
        debugMode: 'false',
    };

    generateFile(
        directory: string,
        className: string,
        source: ConfigSourceResult,
        containerDataClass: string,
        containerDataSpecifier: string,
    ): GenerateStatus {
        const serviceId = AstCachedConfigFileGenerator.CONTRACT_SERVICE_IDS[source.contractName] ?? '';
        const body = this.buildFields(source, containerDataClass);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { ApplicationServiceId } from '${AstCachedConfigFileGenerator.APPLICATION_SERVICE_ID}';`,
            `import { ContainerServiceId } from '${AstCachedConfigFileGenerator.CONTAINER_SERVICE_ID}';`,
            `import { ${containerDataClass} } from '${containerDataSpecifier}';`,
            ...this.buildCopiedImportLines(source),
            '',
            `import type { ApplicationContract } from '${AstCachedConfigFileGenerator.APPLICATION_CONTRACT}';`,
            `import type { ComponentProviderContract } from '${AstCachedConfigFileGenerator.COMPONENT_PROVIDER_CONTRACT}';`,
            `import type { ${source.contractName} } from '${source.contractSpecifier}';`,
            ...this.buildCopiedTypeImportLines(source),
            '',
            `export class ${className} implements ${source.contractName} {`,
            `    static readonly id = ${serviceId};`,
            '',
            ...body,
            '}',
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    /**
     * Render every field of the generated class.
     */
    protected buildFields(source: ConfigSourceResult, containerDataClass: string): string[] {
        const lines: string[] = [];

        for (const [name, value] of Object.entries(source.fields)) {
            if (AstCachedConfigFileGenerator.REPLACED_FIELDS.includes(name)) {
                continue;
            }

            const type = source.types[name];
            const declaration = type !== undefined ? `${name}: ${type}` : name;

            lines.push(`    readonly ${declaration} = ${AstCachedConfigFileGenerator.PINNED_FIELDS[name] ?? value};`);
        }

        lines.push('    readonly providers: ComponentProviderContract[] = [];');
        lines.push('    readonly callbacks: ((app: ApplicationContract) => void)[] = [');
        lines.push('        (app: ApplicationContract): void => {');
        lines.push(
            `            app.getContainer().setSingleton(ContainerServiceId.Data, new ${containerDataClass}());`,
        );
        lines.push('        },');
        lines.push('    ];');

        return lines;
    }

    /**
     * Re-emit the value imports the copied field text still needs.
     */
    protected buildCopiedImportLines(source: ConfigSourceResult): string[] {
        return this.copiedImports(source, false).map((entry) => `import { ${entry.name} } from '${entry.specifier}';`);
    }

    /**
     * Re-emit the type imports the copied field text still needs.
     */
    protected buildCopiedTypeImportLines(source: ConfigSourceResult): string[] {
        return this.copiedImports(source, true).map(
            (entry) => `import type { ${entry.name} } from '${entry.specifier}';`,
        );
    }

    /**
     * Select the source file's imports that the copied text still references.
     *
     * An import used only by `providers` or `callbacks` is dropped with those
     * fields — that is how the component provider import disappears.
     */
    protected copiedImports(source: ConfigSourceResult, isType: boolean): typeof source.imports {
        const copiedText = Object.entries(source.fields)
            .filter(([name]) => !AstCachedConfigFileGenerator.REPLACED_FIELDS.includes(name))
            .filter(([name]) => AstCachedConfigFileGenerator.PINNED_FIELDS[name] === undefined)
            .flatMap(([name, value]) => [value, source.types[name] ?? ''])
            .join('\n');

        const seen = new Set<string>();

        return source.imports.filter((entry) => {
            if (entry.isType !== isType || seen.has(entry.name)) {
                return false;
            }

            // The generated header already binds these names. Emitting them a
            // second time is a duplicate-identifier error.
            if (AstCachedConfigFileGenerator.RESERVED_IMPORT_NAMES.includes(entry.name)) {
                return false;
            }

            if (!new RegExp(`\\b${entry.name}\\b`).test(copiedText)) {
                return false;
            }

            seen.add(entry.name);

            return true;
        });
    }
}
