/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';
import type { CliDataFileGeneratorContract } from '../../Cli/Contract/CliDataFileGeneratorContract.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';

export class AstCliDataFileGenerator extends AstFileGenerator implements CliDataFileGeneratorContract {
    /** The framework classes every generated CLI data file imports as values. */
    protected static readonly FRAMEWORK_IMPORTS: Readonly<Record<string, string>> = {
        CliRoutingData: '@valkyrjaio/valkyrja/Cli/Routing/Data/CliRoutingData.ts',
        Route: '@valkyrjaio/valkyrja/Cli/Routing/Data/Route.ts',
        ArgumentParameter: '@valkyrjaio/valkyrja/Cli/Routing/Data/ArgumentParameter.ts',
        OptionParameter: '@valkyrjaio/valkyrja/Cli/Routing/Data/OptionParameter.ts',
        ArgumentMode: '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentMode.ts',
        ArgumentValueMode: '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentValueMode.ts',
        OptionMode: '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionMode.ts',
        OptionValueMode: '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionValueMode.ts',
    };

    /** The framework types every generated CLI data file imports. */
    protected static readonly FRAMEWORK_TYPE_IMPORTS: Readonly<Record<string, string>> = {
        RouteContract: '@valkyrjaio/valkyrja/Cli/Routing/Data/Contract/RouteContract.ts',
    };

    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImportsBlock = this.buildUserImportsBlock(this.classImportMap, [
            ...Object.keys(AstCliDataFileGenerator.FRAMEWORK_IMPORTS),
            ...Object.keys(AstCliDataFileGenerator.FRAMEWORK_TYPE_IMPORTS),
        ]);

        const contents = this.generateClassContents(routes);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            ...this.buildFrameworkImportLines(AstCliDataFileGenerator.FRAMEWORK_IMPORTS),
            ...this.buildFrameworkImportLines(AstCliDataFileGenerator.FRAMEWORK_TYPE_IMPORTS, true),
            userImportsBlock,
            `export class ${className} extends CliRoutingData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    /**
     * Generate the CLI routing data file from imperative `getRoutes()` route
     * objects — each `new Route(name, description, handler, ...)` is keyed by
     * its command name (the first constructor argument) and emitted verbatim.
     */
    public generateFileFromRoutes(
        directory: string,
        className: string,
        namespace: string,
        routeExprs: readonly ts.Expression[],
    ): GenerateStatus {
        const routes: Record<string, ts.Expression> = {};

        for (const expr of routeExprs) {
            if (!ts.isNewExpression(expr)) {
                continue;
            }

            const key = this.routeKey((expr.arguments ?? [])[0]);

            if (key === undefined) {
                continue;
            }

            routes[key] = expr;
        }

        return this.generateFile(directory, className, namespace, routes);
    }

    /**
     * Derive the map key for a route from its name argument.
     *
     * A literal name keys the map by its own text. A constant reference
     * (`CliCommandName.LIST` — how the framework's own commands name
     * themselves) is kept as a `Class::CASE` marker, so the generated file
     * emits the constant reference as a computed key rather than baking in the
     * value it happens to hold today.
     */
    protected routeKey(nameArg: ts.Expression | undefined): string | undefined {
        if (nameArg === undefined) {
            return undefined;
        }

        if (ts.isStringLiteral(nameArg)) {
            return nameArg.text;
        }

        if (ts.isPropertyAccessExpression(nameArg) && ts.isIdentifier(nameArg.expression)) {
            return `${nameArg.expression.text}::${nameArg.name.text}`;
        }

        return undefined;
    }

    public generateClassContents(routes: Record<string, ts.Expression>): string {
        const entries = Object.entries(routes);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const printedValue = this.printExpr(valueExpr);
            const formattedKey = key.includes('::')
                ? `[${this.printer.printNode(ts.EmitHint.Unspecified, this.buildEnumCaseExpr(key), this.dummySourceFile)}]`
                : `['${key}']`;

            lines.push(`            ${formattedKey}: (): RouteContract => ${printedValue},`);
        }

        return ['super({', ...lines, '        });'].join('\n        ');
    }

    /**
     * Print an expression to source. Parsed nodes (from a `getRoutes()` body)
     * are emitted via their original source text; synthesized nodes (which
     * carry no source positions) are emitted through the printer.
     */
    protected printExpr(expr: ts.Expression): string {
        return expr.pos >= 0
            ? expr.getText()
            : this.printer.printNode(ts.EmitHint.Unspecified, expr, this.dummySourceFile);
    }
}
