/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.js';
import type { CliDataFileGeneratorContract } from '../../Cli/Contract/CliDataFileGeneratorContract.js';
import type { GenerateStatus } from '../../Enum/GenerateStatus.js';

export class AstCliDataFileGenerator extends AstFileGenerator implements CliDataFileGeneratorContract {
    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImports = Object.entries(this.classImportMap)
            .map(([name, specifier]) => `import { ${name} } from '${specifier}';`)
            .join('\n');

        const userImportsBlock = userImports ? `${userImports}\n` : '';

        const contents = this.generateClassContents(routes);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { CliRoutingData } from '@valkyrjaio/valkyrja/Cli/Routing/Data/CliRoutingData.js';`,
            `import { Route } from '@valkyrjaio/valkyrja/Cli/Routing/Data/Route.js';`,
            `import { ArgumentParameter } from '@valkyrjaio/valkyrja/Cli/Routing/Data/ArgumentParameter.js';`,
            `import { OptionParameter } from '@valkyrjaio/valkyrja/Cli/Routing/Data/OptionParameter.js';`,
            `import { ArgumentMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentMode.js';`,
            `import { ArgumentValueMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentValueMode.js';`,
            `import { OptionMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionMode.js';`,
            `import { OptionValueMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionValueMode.js';`,
            `import type { RouteContract } from '@valkyrjaio/valkyrja/Cli/Routing/Data/Contract/RouteContract.js';`,
            userImportsBlock,
            `export class ${className} extends CliRoutingData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(routes: Record<string, ts.Expression>): string {
        const entries = Object.entries(routes);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const keyExpr = this.buildEnumCaseExpr(key);
            const printedKey = this.printer.printNode(ts.EmitHint.Unspecified, keyExpr, this.dummySourceFile);
            const printedValue = this.printer.printNode(ts.EmitHint.Unspecified, valueExpr, this.dummySourceFile);

            const formattedKey = key.includes('::') ? `[${printedKey}]` : `['${printedKey}']`;

            lines.push(`            ${formattedKey}: (): RouteContract => ${printedValue},`);
        }

        return ['super({', '            routes: {', ...lines, '            },', '        });'].join('\n        ');
    }
}
