/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';
import type { CliDataFileGeneratorContract } from '../../Cli/Contract/CliDataFileGeneratorContract.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';

export class AstCliDataFileGenerator extends AstFileGenerator implements CliDataFileGeneratorContract {
    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImportsBlock = this.buildUserImportsBlock(this.classImportMap);

        const contents = this.generateClassContents(routes);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { CliRoutingData } from '@valkyrjaio/valkyrja/Cli/Routing/Data/CliRoutingData.ts';`,
            `import { Route } from '@valkyrjaio/valkyrja/Cli/Routing/Data/Route.ts';`,
            `import { ArgumentParameter } from '@valkyrjaio/valkyrja/Cli/Routing/Data/ArgumentParameter.ts';`,
            `import { OptionParameter } from '@valkyrjaio/valkyrja/Cli/Routing/Data/OptionParameter.ts';`,
            `import { ArgumentMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentMode.ts';`,
            `import { ArgumentValueMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/ArgumentValueMode.ts';`,
            `import { OptionMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionMode.ts';`,
            `import { OptionValueMode } from '@valkyrjaio/valkyrja/Cli/Routing/Enum/OptionValueMode.ts';`,
            `import type { RouteContract } from '@valkyrjaio/valkyrja/Cli/Routing/Data/Contract/RouteContract.ts';`,
            userImportsBlock,
            `export class ${className} extends CliRoutingData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    /**
     * Generate the CLI routing data file from imperative `getRoutes()` route
     * objects — each `new Route(name, description, handler, ...)` is keyed by
     * its command name (the first constructor argument) and emitted verbatim.
     */
    public generateFileFromRoutes(
        directory: string,
        className: string,
        namespace: string,
        routeExprs: readonly ts.Expression[],
    ): GenerateStatus {
        const routes: Record<string, ts.Expression> = {};

        for (const expr of routeExprs) {
            if (!ts.isNewExpression(expr)) {
                continue;
            }

            const nameArg = (expr.arguments ?? [])[0];

            if (nameArg === undefined || !ts.isStringLiteral(nameArg)) {
                continue;
            }

            routes[nameArg.text] = expr;
        }

        return this.generateFile(directory, className, namespace, routes);
    }

    public generateClassContents(routes: Record<string, ts.Expression>): string {
        const entries = Object.entries(routes);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const printedValue = this.printExpr(valueExpr);
            const formattedKey = key.includes('::')
                ? `[${this.printer.printNode(ts.EmitHint.Unspecified, this.buildEnumCaseExpr(key), this.dummySourceFile)}]`
                : `['${key}']`;

            lines.push(`            ${formattedKey}: (): RouteContract => ${printedValue},`);
        }

        return ['super({', ...lines, '        });'].join('\n        ');
    }

    /**
     * Print an expression to source. Parsed nodes (from a `getRoutes()` body)
     * are emitted via their original source text; synthesized nodes (which
     * carry no source positions) are emitted through the printer.
     */
    protected printExpr(expr: ts.Expression): string {
        return expr.pos >= 0
            ? expr.getText()
            : this.printer.printNode(ts.EmitHint.Unspecified, expr, this.dummySourceFile);
    }
}
