/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';

import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';
import type { GrpcDataFileGeneratorContract } from '../../Grpc/Contract/GrpcDataFileGeneratorContract.ts';

export class AstGrpcDataFileGenerator extends AstFileGenerator implements GrpcDataFileGeneratorContract {
    /** The framework classes every generated gRPC data file imports as values. */
    protected static readonly FRAMEWORK_IMPORTS: Readonly<Record<string, string>> = {
        GrpcRoutingData: '@valkyrjaio/valkyrja/Grpc/Routing/Data/GrpcRoutingData.ts',
        Route: '@valkyrjaio/valkyrja/Grpc/Routing/Data/Route.ts',
    };

    /** The framework types every generated gRPC data file imports. */
    protected static readonly FRAMEWORK_TYPE_IMPORTS: Readonly<Record<string, string>> = {
        RouteContract: '@valkyrjaio/valkyrja/Grpc/Routing/Data/Contract/RouteContract.ts',
    };

    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImportsBlock = this.buildUserImportsBlock(this.classImportMap, [
            ...Object.keys(AstGrpcDataFileGenerator.FRAMEWORK_IMPORTS),
            ...Object.keys(AstGrpcDataFileGenerator.FRAMEWORK_TYPE_IMPORTS),
        ]);

        const contents = this.generateClassContents(routes);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            ...this.buildFrameworkImportLines(AstGrpcDataFileGenerator.FRAMEWORK_IMPORTS),
            ...this.buildFrameworkImportLines(AstGrpcDataFileGenerator.FRAMEWORK_TYPE_IMPORTS, true),
            userImportsBlock,
            `export class ${className} extends GrpcRoutingData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    /**
     * Generate the gRPC routing data file from imperative `getRoutes()` route objects — each
     * `new Route(method, handler, ...)` is keyed by its fully-qualified method (the first
     * constructor argument) and emitted verbatim.
     */
    public generateFileFromRoutes(
        directory: string,
        className: string,
        namespace: string,
        routeExprs: readonly ts.Expression[],
    ): GenerateStatus {
        return this.generateMergedFile(directory, className, namespace, {}, routeExprs);
    }

    /**
     * Generate the gRPC routing data file by merging the routes the decorators declare with the
     * routes an imperative `getRoutes()` body constructs. Both are keyed by fully-qualified method
     * into one service map. A decorator entry comes first, and an imperative entry overrides it when
     * the two name one method.
     */
    public generateMergedFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
        routeExprs: readonly ts.Expression[],
    ): GenerateStatus {
        const merged: Record<string, ts.Expression> = { ...routes };

        for (const expr of routeExprs) {
            const key = this.routeKey(expr);

            if (key === undefined) {
                continue;
            }

            merged[key] = expr;
        }

        return this.generateFile(directory, className, namespace, merged);
    }

    /**
     * Derive the service-map key for a route from its method argument.
     *
     * A route expression is frequently a chain — `new Route(...).withClientStreaming(true)` — so the
     * `new` expression is unwrapped from any trailing calls before its first argument is read. A
     * literal method keys the map by its own text; a constant reference is kept as a `Class::CASE`
     * marker so the generated file emits the reference rather than baking in the value it holds
     * today.
     */
    protected routeKey(expr: ts.Expression): string | undefined {
        const newExpr = this.unwrapNewExpression(expr);

        if (newExpr === undefined) {
            return undefined;
        }

        const methodArg = (newExpr.arguments ?? [])[0];

        if (methodArg === undefined) {
            return undefined;
        }

        if (ts.isStringLiteral(methodArg)) {
            return methodArg.text;
        }

        if (ts.isPropertyAccessExpression(methodArg) && ts.isIdentifier(methodArg.expression)) {
            return `${methodArg.expression.text}::${methodArg.name.text}`;
        }

        return undefined;
    }

    /** Walk back through a `with*` builder chain to the `new Route(...)` it was built from. */
    protected unwrapNewExpression(expr: ts.Expression): ts.NewExpression | undefined {
        let current: ts.Expression = expr;

        while (ts.isCallExpression(current) && ts.isPropertyAccessExpression(current.expression)) {
            current = current.expression.expression;
        }

        return ts.isNewExpression(current) ? current : undefined;
    }

    public generateClassContents(routes: Record<string, ts.Expression>): string {
        const entries = Object.entries(routes);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const printedValue = this.printExpr(valueExpr);
            const formattedKey = key.includes('::')
                ? `[${this.printer.printNode(ts.EmitHint.Unspecified, this.buildEnumCaseExpr(key), this.dummySourceFile)}]`
                : `['${key}']`;

            lines.push(`            ${formattedKey}: (): RouteContract => ${printedValue},`);
        }

        return ['super({', ...lines, '        });'].join('\n        ');
    }

    /**
     * Print an expression to source. Parsed nodes (from a `getRoutes()` body) are emitted via their
     * original source text; synthesized nodes (which carry no source positions) go through the
     * printer.
     */
    protected printExpr(expr: ts.Expression): string {
        return expr.pos >= 0
            ? expr.getText()
            : this.printer.printNode(ts.EmitHint.Unspecified, expr, this.dummySourceFile);
    }
}
