/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import ts from 'typescript';

import { DynamicRoute } from '@valkyrja/valkyrja/Http/Routing/Data/DynamicRoute.js';
import { Parameter } from '@valkyrja/valkyrja/Http/Routing/Data/Parameter.js';
import { Regex } from '@valkyrja/valkyrja/Http/Routing/Constant/Regex.js';
import { Processor } from '@valkyrja/valkyrja/Http/Routing/Processor/Processor.js';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.js';
import { GeneratorUnreachableException } from '../../Throwable/Exception/GeneratorUnreachableException.js';
import type { HttpDataFileGeneratorContract } from '../../Http/Contract/HttpDataFileGeneratorContract.js';
import type { GenerateStatus } from '../../Enum/GenerateStatus.js';
import type { HttpParameterData } from '../../../Ast/Data/HttpParameterData.js';
import type { HttpRouteData } from '../../../Ast/Data/HttpRouteData.js';
import type { ProcessorContract } from '@valkyrja/valkyrja/Http/Routing/Processor/Contract/ProcessorContract.js';

export class AstHttpDataFileGenerator extends AstFileGenerator implements HttpDataFileGeneratorContract {
    public classImportMap: Record<string, string> = {};

    protected readonly processor: ProcessorContract;

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile('_dummy.ts', '', ts.ScriptTarget.ESNext, false, ts.ScriptKind.TS);

    public constructor(processor: ProcessorContract = new Processor()) {
        super();
        this.processor = processor;
    }

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        routes: Record<string, ts.Expression>,
        routeData: Record<string, HttpRouteData>,
    ): GenerateStatus {
        const userImports = Object.entries(this.classImportMap)
            .map(([name, specifier]) => `import { ${name} } from '${specifier}';`)
            .join('\n');

        const userImportsBlock = userImports ? `${userImports}\n` : '';

        const routesContent = this.getRoutesAsContent(routes, routeData);
        const paths = this.printNestedObject(this.buildPaths(routeData));
        const dynamicPaths = this.printNestedObject(this.buildDynamicPaths(routeData));
        const regexes = this.printNestedObject(this.buildRegexes(routeData));

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { HttpRoutingData } from '@valkyrja/valkyrja/Http/Routing/Data/HttpRoutingData.js';`,
            `import { DynamicRoute } from '@valkyrja/valkyrja/Http/Routing/Data/DynamicRoute.js';`,
            `import { Route } from '@valkyrja/valkyrja/Http/Routing/Data/Route.js';`,
            `import { Parameter } from '@valkyrja/valkyrja/Http/Routing/Data/Parameter.js';`,
            `import { RequestMethod } from '@valkyrja/valkyrja/Http/Message/Enum/RequestMethod.js';`,
            `import { Regex } from '@valkyrja/valkyrja/Http/Routing/Constant/Regex.js';`,
            `import type { RouteContract } from '@valkyrja/valkyrja/Http/Routing/Data/Contract/RouteContract.js';`,
            userImportsBlock,
            `export class ${className} extends HttpRoutingData {`,
            `    constructor() {`,
            `        super(`,
            `            ${routesContent},`,
            `            ${paths},`,
            `            ${dynamicPaths},`,
            `            ${regexes},`,
            `        );`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(routes: Record<string, ts.Expression>, routeData: Record<string, HttpRouteData>): string {
        const routesContent = this.getRoutesAsContent(routes, routeData);
        const paths = this.printNestedObject(this.buildPaths(routeData));
        const dynamicPaths = this.printNestedObject(this.buildDynamicPaths(routeData));
        const regexes = this.printNestedObject(this.buildRegexes(routeData));

        return [
            'super(',
            `            ${routesContent},`,
            `            ${paths},`,
            `            ${dynamicPaths},`,
            `            ${regexes},`,
            '        );',
        ].join('\n        ');
    }

    protected buildPaths(routeData: Record<string, HttpRouteData>): Record<string, Record<string, string>> {
        const paths: Record<string, Record<string, string>> = {};

        for (const [name, data] of Object.entries(routeData)) {
            if (data.isDynamic) {
                continue;
            }

            const path = this.normalizePath(data.path);

            for (const method of this.extractMethodNames(data.requestMethods)) {
                if (paths[method] === undefined) {
                    paths[method] = {};
                }

                paths[method][path] = name;
            }
        }

        return paths;
    }

    protected buildDynamicPaths(routeData: Record<string, HttpRouteData>): Record<string, Record<string, string>> {
        const dynamicPaths: Record<string, Record<string, string>> = {};

        for (const [name, data] of Object.entries(routeData)) {
            if (!data.isDynamic) {
                continue;
            }

            const path = this.normalizePath(data.path);

            for (const method of this.extractMethodNames(data.requestMethods)) {
                if (dynamicPaths[method] === undefined) {
                    dynamicPaths[method] = {};
                }

                dynamicPaths[method][path] = name;
            }
        }

        return dynamicPaths;
    }

    protected buildRegexes(routeData: Record<string, HttpRouteData>): Record<string, Record<string, string>> {
        const regexes: Record<string, Record<string, string>> = {};

        for (const [name, data] of Object.entries(routeData)) {
            if (!data.isDynamic || data.parameters.length === 0) {
                continue;
            }

            const regex = this.computeRegex(data);

            if (regex === '') {
                continue;
            }

            for (const method of this.extractMethodNames(data.requestMethods)) {
                if (regexes[method] === undefined) {
                    regexes[method] = {};
                }

                regexes[method][regex] = name;
            }
        }

        return regexes;
    }

    protected buildNestedStringArrayExpr(data: Record<string, Record<string, string>>): ts.ObjectLiteralExpression {
        const outerProps: ts.PropertyAssignment[] = [];

        for (const [outerKey, innerMap] of Object.entries(data)) {
            const innerProps: ts.PropertyAssignment[] = [];

            for (const [innerKey, value] of Object.entries(innerMap)) {
                innerProps.push(
                    ts.factory.createPropertyAssignment(
                        ts.factory.createStringLiteral(innerKey),
                        ts.factory.createStringLiteral(value),
                    ),
                );
            }

            outerProps.push(
                ts.factory.createPropertyAssignment(
                    ts.factory.createStringLiteral(outerKey),
                    ts.factory.createObjectLiteralExpression(innerProps, true),
                ),
            );
        }

        return ts.factory.createObjectLiteralExpression(outerProps, true);
    }

    protected printNestedObject(data: Record<string, Record<string, string>>): string {
        return this.printer.printNode(
            ts.EmitHint.Unspecified,
            this.buildNestedStringArrayExpr(data),
            this.dummySourceFile,
        );
    }

    protected computeRegex(data: HttpRouteData): string {
        const parameters = data.parameters.map((p) => this.buildParameter(p));

        const route = new DynamicRoute(
            data.path !== '' ? data.path : '/',
            data.name !== '' ? data.name : 'temp',
            '',
            parameters,
            (): never => {
                throw new GeneratorUnreachableException('unreachable');
            },
        );

        const processed = this.processor.route(route);

        if ('getRegex' in processed && typeof (processed as DynamicRoute).getRegex === 'function') {
            return (processed as DynamicRoute).getRegex();
        }

        return '';
    }

    protected buildParameter(data: HttpParameterData): Parameter {
        let regex = data.regex;

        if (regex.includes('::')) {
            const pos = regex.lastIndexOf('::');
            const className = regex.substring(0, pos);
            const propName = regex.substring(pos + 2);

            if (className === 'Regex') {
                const resolved = (Regex as unknown as Record<string, string>)[propName];

                if (typeof resolved === 'string' && resolved !== '') {
                    regex = resolved;
                }
            }
        }

        return new Parameter(data.name, regex, null, data.isOptional, data.shouldCapture);
    }

    protected normalizePath(path: string): string {
        return '/' + path.replace(/^\/+|\/+$/g, '');
    }

    protected extractMethodNames(requestMethods: readonly string[]): string[] {
        const methods: string[] = [];

        for (const method of requestMethods) {
            const pos = method.lastIndexOf('::');

            if (pos !== -1) {
                methods.push(method.substring(pos + 2));
            }
        }

        return methods;
    }

    protected getRoutesAsContent(routes: Record<string, ts.Expression>, routeData: Record<string, HttpRouteData>): string {
        const entries = Object.entries(routes);

        if (entries.length === 0) {
            return '{}';
        }

        const lines: string[] = [];

        for (const [key, routeExpr] of entries) {
            const data = routeData[key] ?? null;
            let expr = routeExpr;

            if (data !== null && data.isDynamic && ts.isNewExpression(expr)) {
                const computedRegex = data.parameters.length > 0 ? this.computeRegex(data) : '';
                const args = [...(expr.arguments ?? []), ts.factory.createStringLiteral(computedRegex)];
                expr = ts.factory.createNewExpression(expr.expression, expr.typeArguments, args);
            }

            const keyExpr = this.buildEnumCaseExpr(key);
            const printedKey = this.printer.printNode(ts.EmitHint.Unspecified, keyExpr, this.dummySourceFile);
            const printedRoute = this.printer.printNode(ts.EmitHint.Unspecified, expr, this.dummySourceFile);

            const formattedKey = key.includes('::') ? `[${printedKey}]` : `['${printedKey}']`;

            lines.push(`            ${formattedKey}: (): RouteContract => ${printedRoute},`);
        }

        return [
            '{',
            ...lines,
            '        }',
        ].join('\n        ');
    }
}
