/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.js';
import type { EventDataFileGeneratorContract } from '../../Event/Contract/EventDataFileGeneratorContract.js';
import type { GenerateStatus } from '../../Enum/GenerateStatus.js';

export class AstEventDataFileGenerator extends AstFileGenerator implements EventDataFileGeneratorContract {
    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        listeners: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImports = Object.entries(this.classImportMap)
            .map(([name, specifier]) => `import { ${name} } from '${specifier}';`)
            .join('\n');

        const userImportsBlock = userImports ? `${userImports}\n` : '';

        const contents = this.generateClassContents(listeners);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { EventData } from '@valkyrjaio/valkyrja/Event/Data/EventData.js';`,
            `import { Listener } from '@valkyrjaio/valkyrja/Event/Data/Listener.js';`,
            `import type { ListenerContract } from '@valkyrjaio/valkyrja/Event/Data/Contract/ListenerContract.js';`,
            userImportsBlock,
            `export class ${className} extends EventData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(listeners: Record<string, ts.Expression>): string {
        const entries = Object.entries(listeners);

        if (entries.length === 0) {
            return 'super();';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const printed = this.printer.printNode(ts.EmitHint.Unspecified, valueExpr, this.dummySourceFile);
            lines.push(`            ['${key}']: (): ListenerContract => ${printed},`);
        }

        return ['super(', '            {},', '            {', ...lines, '            },', '        );'].join(
            '\n        ',
        );
    }
}
