/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';
import type { EventDataFileGeneratorContract } from '../../Event/Contract/EventDataFileGeneratorContract.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';

export class AstEventDataFileGenerator extends AstFileGenerator implements EventDataFileGeneratorContract {
    /** The framework class every generated event data file imports as a value. */
    protected static readonly FRAMEWORK_IMPORTS: Readonly<Record<string, string>> = {
        EventData: '@valkyrjaio/valkyrja/Event/Data/EventData.ts',
    };

    /** The framework classes a generated event data file imports only when it holds listeners. */
    protected static readonly LISTENER_IMPORTS: Readonly<Record<string, string>> = {
        Listener: '@valkyrjaio/valkyrja/Event/Data/Listener.ts',
    };

    /** The framework types a generated event data file imports only when it holds listeners. */
    protected static readonly LISTENER_TYPE_IMPORTS: Readonly<Record<string, string>> = {
        ListenerContract: '@valkyrjaio/valkyrja/Event/Data/Contract/ListenerContract.ts',
    };

    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        listeners: Record<string, ts.Expression>,
    ): GenerateStatus {
        const userImportsBlock = this.buildUserImportsBlock(this.classImportMap, [
            ...Object.keys(AstEventDataFileGenerator.FRAMEWORK_IMPORTS),
            ...Object.keys(AstEventDataFileGenerator.LISTENER_IMPORTS),
            ...Object.keys(AstEventDataFileGenerator.LISTENER_TYPE_IMPORTS),
        ]);

        const contents = this.generateClassContents(listeners);

        // The Listener / ListenerContract imports are only referenced by the
        // generated listener closures — omit them when there are no listeners
        // so empty event data does not carry unused (and unresolved) imports.
        const listenerImports =
            Object.keys(listeners).length > 0
                ? [
                      ...this.buildFrameworkImportLines(AstEventDataFileGenerator.LISTENER_IMPORTS),
                      ...this.buildFrameworkImportLines(AstEventDataFileGenerator.LISTENER_TYPE_IMPORTS, true),
                  ]
                : [];

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            ...this.buildFrameworkImportLines(AstEventDataFileGenerator.FRAMEWORK_IMPORTS),
            ...listenerImports,
            userImportsBlock,
            `export class ${className} extends EventData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(listeners: Record<string, ts.Expression>): string {
        const entries = Object.entries(listeners);

        if (entries.length === 0) {
            return 'super();';
        }

        const lines: string[] = [];

        for (const [key, valueExpr] of entries) {
            const printed = this.printer.printNode(ts.EmitHint.Unspecified, valueExpr, this.dummySourceFile);
            lines.push(`            ['${key}']: (): ListenerContract => ${printed},`);
        }

        return ['super(', '            {},', '            {', ...lines, '            },', '        );'].join(
            '\n        ',
        );
    }
}
