/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';
import type { ContainerDataFileGeneratorContract } from '../../Container/Contract/ContainerDataFileGeneratorContract.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';

export class AstContainerDataFileGenerator extends AstFileGenerator implements ContainerDataFileGeneratorContract {
    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        publishers: Readonly<Record<string, readonly [string, string]>>,
    ): GenerateStatus {
        const userImports = Object.entries(this.classImportMap)
            .map(([name, specifier]) => `import { ${name} } from '${specifier}';`)
            .join('\n');

        const userImportsBlock = userImports ? `${userImports}\n` : '';

        const contents = this.generateClassContents(publishers);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            `import { ContainerData } from '@valkyrjaio/valkyrja/Container/Data/ContainerData.ts';`,
            `import type { ContainerContract } from '@valkyrjaio/valkyrja/Container/Manager/Contract/ContainerContract.ts';`,
            userImportsBlock,
            `export class ${className} extends ContainerData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(publishers: Readonly<Record<string, readonly [string, string]>>): string {
        const entries = Object.entries(publishers);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [serviceId, [providerClass, methodName]] of entries) {
            const keyExpr = this.buildEnumCaseExpr(serviceId);
            const printedKey = this.printer.printNode(ts.EmitHint.Unspecified, keyExpr, this.dummySourceFile);

            const shortProviderClass = providerClass.slice(providerClass.lastIndexOf('\\') + 1);

            const formattedKey = serviceId.includes('::') ? `[${printedKey}]` : `['${printedKey}']`;

            lines.push(
                `            ${formattedKey}: (container: ContainerContract) => ${shortProviderClass}.${methodName}(container),`,
            );
        }

        return ['super({', '            deferredCallback: {', ...lines, '            },', '        });'].join(
            '\n        ',
        );
    }
}
