/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { ts } from 'ts-morph';

import { AstFileGenerator } from '../../Abstract/AstFileGenerator.ts';
import type { ContainerDataFileGeneratorContract } from '../../Container/Contract/ContainerDataFileGeneratorContract.ts';
import type { GenerateStatus } from '../../Enum/GenerateStatus.ts';

export class AstContainerDataFileGenerator extends AstFileGenerator implements ContainerDataFileGeneratorContract {
    /** The framework class every generated container data file imports as a value. */
    protected static readonly FRAMEWORK_IMPORTS: Readonly<Record<string, string>> = {
        ContainerData: '@valkyrjaio/valkyrja/Container/Data/ContainerData.ts',
    };

    /** The framework type every generated container data file imports. */
    protected static readonly FRAMEWORK_TYPE_IMPORTS: Readonly<Record<string, string>> = {
        ContainerContract: '@valkyrjaio/valkyrja/Container/Manager/Contract/ContainerContract.ts',
    };

    public classImportMap: Record<string, string> = {};

    private readonly printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

    private readonly dummySourceFile = ts.createSourceFile(
        '_dummy.ts',
        '',
        ts.ScriptTarget.ESNext,
        false,
        ts.ScriptKind.TS,
    );

    public generateFile(
        directory: string,
        className: string,
        namespace: string,
        publishers: Readonly<Record<string, readonly [string, string]>>,
    ): GenerateStatus {
        const userImportsBlock = this.buildUserImportsBlock(this.classImportMap, [
            ...Object.keys(AstContainerDataFileGenerator.FRAMEWORK_IMPORTS),
            ...Object.keys(AstContainerDataFileGenerator.FRAMEWORK_TYPE_IMPORTS),
        ]);

        const contents = this.generateClassContents(publishers);

        const data = [
            '// This file was automatically generated by Sindri.',
            '',
            ...this.buildFrameworkImportLines(AstContainerDataFileGenerator.FRAMEWORK_IMPORTS),
            ...this.buildFrameworkImportLines(AstContainerDataFileGenerator.FRAMEWORK_TYPE_IMPORTS, true),
            userImportsBlock,
            `export class ${className} extends ContainerData {`,
            `    constructor() {`,
            `        ${contents}`,
            `    }`,
            `}`,
            '',
        ].join('\n');

        return this.writeFile(directory, className, data);
    }

    public generateClassContents(publishers: Readonly<Record<string, readonly [string, string]>>): string {
        const entries = Object.entries(publishers);

        if (entries.length === 0) {
            return 'super({});';
        }

        const lines: string[] = [];

        for (const [serviceId, [providerClass, methodName]] of entries) {
            const shortProviderClass = providerClass.slice(providerClass.lastIndexOf('\\') + 1);

            const formattedKey = serviceId.includes('::')
                ? `[${this.printer.printNode(ts.EmitHint.Unspecified, this.buildEnumCaseExpr(serviceId), this.dummySourceFile)}]`
                : `['${serviceId}']`;

            lines.push(
                `            ${formattedKey}: (container: ContainerContract) => ${shortProviderClass}.${methodName}(container),`,
            );
        }

        return ['super({', '            deferredCallback: {', ...lines, '            },', '        });'].join(
            '\n        ',
        );
    }
}
